=== fredboudon/plantgl-jupyter/pgljupyter/schema/lpy.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "L-Py",
    "type": "object",
    "required": ["schema"],
    "properties": {
        "schema": {
            "enum": ["lpy"]
        },
        "authors": {
            "type": "string"
        },
        "institutes": {
            "type": "string"
        },
        "copyright": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "references": {
            "type": "string"
        },
        "animation_timestep": {
            "type": "number",
            "exclusiveMinimum": 0
        },
        "scalars": {
            "type": "object",
            "patternProperties": {
                "^[^\\d\\W]\\w*\\Z": {
                    "$ref": "scalar.json"
                }
            },
            "additionalProperties": false
        },
        "materials": {
            "type": "object",
            "patternProperties": {
                "^[^\\d\\W]\\w*\\Z": {
                    "$ref": "material.json"
                }
            },
            "additionalProperties": false
        },
        "functions": {
            "type": "object",
            "patternProperties": {
                "^[^\\d\\W]\\w*\\Z": {
                    "$ref": "function.json"
                }
            },
            "additionalProperties": false
        },
        "curves": {
            "type": "object",
            "patternProperties": {
                "^[^\\d\\W]\\w*\\Z": {
                    "$ref": "curve.json"
                }
            },
            "additionalProperties": false
        }
    }
}

=== fredboudon/plantgl-jupyter/examples/lpy/dynamicprofile.json
{
    "schema": "lpy",
    "materials": {
        "color": {
            "index": 2,
            "ambient": [
                73,
                92,
                51
            ],
            "diffuse": 0.393204,
            "specular": [
                71,
                143,
                159
            ],
            "emission": [
                34,
                39,
                57
            ],
            "transparency": 0.58
        }
    },
    "functions": {
        "leafwidth": {
            "NurbsCurve2D": [
                [
                    0.0,
                    0.0126800537109375
                ],
                [
                    0.2197443181818182,
                    0.589100508256392
                ],
                [
                    0.3333806818181817,
                    0.080009599165483
                ],
                [
                    1.0,
                    0.0035891446200284616
                ]
            ]
        }
    },
    "curves": {
        "profile": {
            "NurbsCurve2D": [
                [
                    -0.5671717124097543,
                    0.010349592264448926
                ],
                [
                    -0.22910935625475073,
                    0.4644631599068219
                ],
                [
                    -0.022235388893652397,
                    -0.2469814403066735
                ],
                [
                    0.1846385784674459,
                    0.46950886642782436
                ],
                [
                    0.4217867849545588,
                    0.015395298785451317
                ]
            ]
        },
        "axis1": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.49552241639640116,
                    0.21742664949363016
                ],
                [
                    -0.21352716185094664,
                    0.22279798767544834
                ],
                [
                    -0.18667049143188477,
                    0.02405847494817561
                ],
                [
                    -0.36929596912367396,
                    0.03748682040272106
                ],
                [
                    -0.33438227094185574,
                    0.1126855549481756
                ]
            ]
        },
        "axis2": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.4046170117111899,
                    0.12702123069326227
                ],
                [
                    -0.32102931625664455,
                    0.213305303420535
                ],
                [
                    -0.18621045262028096,
                    0.22409081251144408
                ],
                [
                    -0.1241937753475536,
                    0.14859224887508046
                ],
                [
                    -0.14306841625664454,
                    0.03264802614780772
                ]
            ]
        },
        "axis3": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.44177944697623517,
                    0.10954939207802514
                ],
                [
                    -0.38806606515805336,
                    0.2035478102598433
                ],
                [
                    -0.31018166152168974,
                    0.2465185157143888
                ],
                [
                    -0.21618322284984254,
                    0.25994686116893423
                ],
                [
                    -0.15441287473899162,
                    0.14177742116893421
                ]
            ]
        },
        "axis4": {
            "NurbsCurve2D": [
                [
                    -0.4523769271054077,
                    -0.005600587799786658
                ],
                [
                    -0.3767718616508623,
                    0.06190393492748608
                ],
                [
                    -0.31736788165086227,
                    0.11860773401839517
                ],
                [
                    -0.25256353983268054,
                    0.16991117129112243
                ],
                [
                    -0.19585974074177137,
                    0.23471551310930427
                ],
                [
                    -0.11903621541579021,
                    0.3431250146903886
                ]
            ]
        },
        "axis5": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.42353109378640263,
                    0.09292297178631177
                ],
                [
                    -0.3614269431776844,
                    0.1631276754226754
                ],
                [
                    -0.311815335240922,
                    0.27436190918077913
                ],
                [
                    -0.2510197531605952,
                    0.39595307334143276
                ],
                [
                    -0.3878098128413305,
                    0.4529489315417391
                ]
            ]
        },
        "axis6": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.4096211298461914,
                    0.11916335514498623
                ],
                [
                    -0.33890305711891866,
                    0.21345411878134987
                ],
                [
                    -0.3254329480280095,
                    0.30774488241771353
                ],
                [
                    -0.377214541759461,
                    0.39738799966748417
                ],
                [
                    -0.49416205043080635,
                    0.45168505726489455
                ]
            ]
        },
        "axis7": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.45381259264846796,
                    0.12013621899284291
                ],
                [
                    -0.3893521988258032,
                    0.2189754895209291
                ],
                [
                    -0.43232579470757976,
                    0.3350041984017258
                ],
                [
                    -0.5612465823529095,
                    0.3822751538716801
                ],
                [
                    -0.6343016953519296,
                    0.2920306025199492
                ]
            ]
        },
        "axis8": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.4443799997170015,
                    0.08445238120155335
                ],
                [
                    -0.3881438269897287,
                    0.1469370175651897
                ],
                [
                    -0.4706173170331641,
                    0.3395544757251096
                ],
                [
                    -0.6965523668082574,
                    0.3107991057537341
                ],
                [
                    -0.6965523668082574,
                    0.1505906159132135
                ]
            ]
        },
        "axis9": {
            "NurbsCurve2D": [
                [
                    -0.5,
                    0.0
                ],
                [
                    -0.4669615846065175,
                    0.10362475759086609
                ],
                [
                    -0.42851562474708466,
                    0.29118498972390533
                ],
                [
                    -0.5781451680983921,
                    0.3950943948289799
                ],
                [
                    -0.7236183352454963,
                    0.2496212276818755
                ],
                [
                    -0.5906142967110011,
                    0.14986819878100388
                ]
            ]
        }
    }
}

=== fredboudon/plantgl-jupyter/examples/lpy/leuwenberg.json
{
    "schema": "lpy",
    "scalars": {
        "leafduration": {
            "type": "Integer",
            "value": 8,
            "min": 1,
            "max": 10,
            "step": 1
        },
        "leafold": {
            "type": "Integer",
            "value": 3,
            "min": 1,
            "max": 10,
            "step": 1
        },
        "maxorder": {
            "type": "Integer",
            "value": 6,
            "min": 1,
            "max": 10,
            "step": 1
        },
        "radinc": {
            "type": "Float",
            "value": 0.04,
            "min": 0.01,
            "max": 0.1,
            "step": 0.01
        }
    },
    "materials": {
        "color_1": {
            "index": 1,
            "ambient": [
                96,
                77,
                62
            ],
            "diffuse": 0.0,
            "specular": [
                71,
                143,
                159
            ],
            "emission": [
                31,
                72,
                219
            ],
            "transparency": 0.0,
            "shininess": 0.7
        },
        "color_2": {
            "index": 2,
            "ambient": [
                194,
                81,
                115
            ],
            "diffuse": 1.0,
            "specular": [
                71,
                143,
                159
            ],
            "emission": [
                31,
                72,
                219
            ],
            "transparency": 1.0
        },
        "color_4": {
            "index": 4,
            "ambient": [
                225,
                160,
                20
            ],
            "diffuse": 1.0,
            "specular": [
                71,
                143,
                159
            ],
            "emission": [
                31,
                72,
                219
            ],
            "transparency": 1.0
        }
    },
    "functions": {},
    "curves": {
        "BezierCurve2D_0": {
            "BezierCurve2D": [
                [
                    -0.5,
                    0
                ],
                [
                    -0.25,
                    0.25
                ],
                [
                    0.25,
                    -0.25
                ],
                [
                    0.5,
                    0
                ]
            ]
        }
    }
}
